### ISSUE TITLE
Use GET endpoint instead of POST method

### ISSUE THREAD

**Issue by njahn82** [ropensci/roadoi#3]
from @jasonpriem #1 

> We completely rebuilt a lot of oaDOI over the last month in order to deal with the massive traffic we were getting. As part of that, we found that is was actually easier to scale (using Heroku Dynos) if we got one DOI per request, using the GET endpoint. That's reflected in the new API docs, which no longer mention the POST. It's also for the most part easier for people to use.

> So, if you get the chance or have the interest, we'd love if this wrapper could use the GET endpoint as well.

**Comment by njahn82** [comment]
@jasonpriem I dropped the POST methods. Now only the GET method is supported. Hope, it works for you

**Comment by njahn82** [comment]
here's the commit db71f1fddf40e80e6d1bb08c2c2e7db2191ae317

**Comment by jasonpriem** [comment]
Wow, done so quickly! Wonderful. Looks fantastic. So stoked to be able to point people to this.

**Comment by njahn82** [comment]
Great, your API has made it very easy to write and maintain this client. Will submit it to CRAN with the beginning of next year.

Have a fantastic new year!
